# Generated by Django 5.1.7 on 2025-04-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buy_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('ticker', models.CharField(default='UNKNOWN', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='api_asset_ticker_c7ae47_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='api.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'date'], name='api_histori_asset_i_5a7cfe_idx'), models.Index(fields=['date'], name='api_histori_date_99725a_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
