# Generated by Django 5.1.7 on 2025-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='api_asset_ticker_c7ae47_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicalprice',
            name='api_histori_asset_i_5a7cfe_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicalprice',
            name='api_histori_date_99725a_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.AddField(
            model_name='asset',
            name='instrument_type',
            field=models.CharField(choices=[('shares', 'Shares'), ('bonds', 'Bonds'), ('etf', 'ETF')], default='shares', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
