# Generated by Django 5.1.7 on 2025-04-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_asset_api_asset_ticker_c7ae47_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
